package com.chillpavz.seamlessoresmatrix.content;

import com.chillpavz.seamlessoresmatrix.platform.Services;
import net.minecraft.resources.Identifier;
import net.minecraft.util.valueproviders.ConstantInt;
import net.minecraft.util.valueproviders.IntProvider;
import net.minecraft.util.valueproviders.UniformInt;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * An ore that a host stone can swallow: the eight overworld ores, the two nether ores that Create's
 * nether strata reach, Create's zinc, and every other ore mod's ores that reach a host on 26.x.
 *
 * <p>Each kind stands for EVERY one of its forms: a limestone blob placed over deepslate iron leaves a
 * deepslate iron ore inside limestone just as surely as it does a stone one, and both become the same
 * limestone iron ore. The nether ores have one form only.
 *
 * <p>XP matches the ore's own, which vanilla keeps the same for a stone ore and its deepslate form. A
 * few modded ores do not (Mythic Metals' morkite and unobtainium), so a kind may carry a deepslate XP.
 *
 * <p>The modded kinds are generated by tools/generate_assets.py from tools/modded_pairs.json, which
 * takes each ore's forms, XP and strength from Seamless Ores (itself read from every ore mod's jar).
 */
public enum OreKind {
    COAL("coal", UniformInt.of(0, 2)),
    IRON("iron", ConstantInt.of(0)),
    COPPER("copper", ConstantInt.of(0)),
    GOLD("gold", ConstantInt.of(0)),
    REDSTONE("redstone", ConstantInt.of(0)),
    EMERALD("emerald", UniformInt.of(3, 7)),
    LAPIS("lapis", UniformInt.of(2, 5)),
    DIAMOND("diamond", UniformInt.of(3, 7)),
    // Create's zinc: a variant exists only while Create is installed. Create builds its zinc ores from
    // gold ore's properties, so ours do too; the drops are Create's own.
    ZINC("zinc", ConstantInt.of(0), "create",
            Identifier.fromNamespaceAndPath("create", "zinc_ore"),
            Identifier.fromNamespaceAndPath("create", "deepslate_zinc_ore"),
            Identifier.withDefaultNamespace("gold_ore"), Identifier.withDefaultNamespace("deepslate_gold_ore"),
            List.of("granite", "diorite", "andesite", "tuff")),
    NETHER_GOLD("nether_gold", UniformInt.of(0, 1), null,
            Identifier.withDefaultNamespace("nether_gold_ore"), null,
            Identifier.withDefaultNamespace("nether_gold_ore"), null,
            List.of("basalt", "blackstone")),
    QUARTZ("quartz", UniformInt.of(2, 5), null,
            Identifier.withDefaultNamespace("nether_quartz_ore"), null,
            Identifier.withDefaultNamespace("nether_quartz_ore"), null,
            List.of("basalt", "blackstone")),
    // BEGIN GENERATED modded kinds (tools/generate_assets.py, from tools/modded_pairs.json)
    ENERGIZED_TIN("energized_tin", "energizedpower", "energized_tin", false,
            ConstantInt.of(0), null, null,
            "energizedpower:tin_ore", "energizedpower:deepslate_tin_ore"),
    PROSPERITY("prosperity", "mysticalagriculture", "prosperity", false,
            UniformInt.of(2, 5), null, null,
            "mysticalagriculture:prosperity_ore", "mysticalagriculture:deepslate_prosperity_ore"),
    ADAMANTITE("adamantite", "mythicmetals", "adamantite", false,
            ConstantInt.of(0), null, new float[] {4.0F, 5.0F, 6.0F, 12.0F},
            "mythicmetals:adamantite_ore", "mythicmetals:deepslate_adamantite_ore"),
    AQUARIUM("aquarium", "mythicmetals", "aquarium", false,
            ConstantInt.of(0), null, new float[] {4.0F, 5.0F, 4.0F, 5.0F},
            "mythicmetals:aquarium_ore"),
    BANGLUM("banglum", "mythicmetals", "banglum", false,
            ConstantInt.of(0), null, new float[] {5.0F, 5.5F, 5.0F, 5.5F},
            "mythicmetals:banglum_ore"),
    CARMOT("carmot", "mythicmetals", "carmot", false,
            ConstantInt.of(0), null, new float[] {5.5F, 6.5F, 6.5F, 12.0F},
            "mythicmetals:carmot_ore", "mythicmetals:deepslate_carmot_ore"),
    KYBER("kyber", "mythicmetals", "kyber", false,
            ConstantInt.of(0), null, new float[] {3.0F, 4.0F, 3.0F, 4.0F},
            "mythicmetals:kyber_ore"),
    MANGANESE("manganese", "mythicmetals", "manganese", false,
            ConstantInt.of(0), null, new float[] {3.0F, 4.0F, 3.0F, 4.0F},
            "mythicmetals:manganese_ore"),
    MIDAS_GOLD("midas_gold", "mythicmetals", "midas_gold", true,
            ConstantInt.of(0), null, new float[] {4.0F, 5.0F, 4.0F, 5.0F},
            "mythicmetals:midas_gold_ore"),
    MORKITE("morkite", "mythicmetals", "morkite", false,
            UniformInt.of(1, 2), UniformInt.of(1, 3), new float[] {3.0F, 4.0F, 3.0F, 4.0F},
            "mythicmetals:morkite_ore", "mythicmetals:deepslate_morkite_ore"),
    MYTHRIL("mythril", "mythicmetals", "mythril", false,
            ConstantInt.of(0), null, new float[] {5.0F, 6.0F, 5.5F, 6.5F},
            "mythicmetals:mythril_ore", "mythicmetals:deepslate_mythril_ore"),
    NETHER_BANGLUM("nether_banglum", "mythicmetals", "banglum", true,
            ConstantInt.of(0), null, new float[] {5.0F, 5.5F, 5.0F, 5.5F},
            "mythicmetals:nether_banglum_ore"),
    ORICHALCUM("orichalcum", "mythicmetals", "orichalcum", false,
            ConstantInt.of(0), null, new float[] {5.5F, 6.5F, 5.5F, 6.5F},
            "mythicmetals:orichalcum_ore", "mythicmetals:deepslate_orichalcum_ore"),
    OSMIUM("osmium", "mythicmetals", "osmium", false,
            ConstantInt.of(0), null, new float[] {4.0F, 5.0F, 4.0F, 5.0F},
            "mythicmetals:osmium_ore"),
    PALLADIUM("palladium", "mythicmetals", "palladium", true,
            ConstantInt.of(0), null, new float[] {5.0F, 6.0F, 5.0F, 6.0F},
            "mythicmetals:palladium_ore"),
    PLATINUM("platinum", "mythicmetals", "platinum", false,
            ConstantInt.of(0), null, new float[] {3.5F, 4.5F, 3.5F, 4.5F},
            "mythicmetals:platinum_ore"),
    PROMETHEUM("prometheum", "mythicmetals", "prometheum", false,
            ConstantInt.of(0), null, new float[] {5.0F, 6.0F, 6.0F, 7.0F},
            "mythicmetals:prometheum_ore", "mythicmetals:deepslate_prometheum_ore"),
    QUADRILLUM("quadrillum", "mythicmetals", "quadrillum", false,
            ConstantInt.of(0), null, new float[] {3.5F, 4.5F, 3.5F, 4.5F},
            "mythicmetals:quadrillum_ore"),
    RUNITE("runite", "mythicmetals", "runite", false,
            ConstantInt.of(0), null, new float[] {8.0F, 9.0F, 9.0F, 10.0F},
            "mythicmetals:runite_ore", "mythicmetals:deepslate_runite_ore"),
    SILVER("silver", "mythicmetals", "silver", false,
            ConstantInt.of(0), null, new float[] {2.5F, 3.5F, 2.5F, 3.5F},
            "mythicmetals:silver_ore"),
    STARRITE("starrite", "mythicmetals", "starrite", false,
            ConstantInt.of(0), null, new float[] {5.0F, 6.0F, 5.0F, 6.0F},
            "mythicmetals:starrite_ore"),
    STORMYX("stormyx", "mythicmetals", "stormyx", true,
            UniformInt.of(2, 4), null, new float[] {5.0F, 6.0F, 5.0F, 6.0F},
            "mythicmetals:stormyx_ore"),
    TIN("tin", "mythicmetals", "tin", false,
            ConstantInt.of(0), null, new float[] {2.0F, 3.0F, 2.0F, 3.0F},
            "mythicmetals:tin_ore"),
    UNOBTAINIUM("unobtainium", "mythicmetals", "unobtainium", false,
            ConstantInt.of(0), UniformInt.of(4, 7), new float[] {16.0F, 13000.0F, 21.0F, 14000.0F},
            "mythicmetals:unobtainium_ore", "mythicmetals:deepslate_unobtainium_ore"),
    AQUAMARINE("aquamarine", "mythicupgrades", "aquamarine", false,
            UniformInt.of(6, 14), null, null,
            "mythicupgrades:aquamarine_ore", "mythicupgrades:deepslate_aquamarine_ore"),
    CITRINE("citrine", "mythicupgrades", "citrine", false,
            UniformInt.of(6, 14), null, null,
            "mythicupgrades:citrine_ore", "mythicupgrades:deepslate_citrine_ore"),
    NECOIUM("necoium", "mythicupgrades", "necoium", false,
            ConstantInt.of(0), null, null,
            "mythicupgrades:necoium_ore", "mythicupgrades:deepslate_necoium_ore"),
    PERIDOT("peridot", "mythicupgrades", "peridot", false,
            UniformInt.of(6, 14), null, null,
            "mythicupgrades:peridot_ore", "mythicupgrades:deepslate_peridot_ore"),
    RUBY("ruby", "mythicupgrades", "ruby", true,
            UniformInt.of(4, 10), null, null,
            "mythicupgrades:ruby_ore"),
    SAPPHIRE("sapphire", "mythicupgrades", "sapphire", true,
            UniformInt.of(4, 10), null, null,
            "mythicupgrades:sapphire_ore"),
    TOPAZ("topaz", "mythicupgrades", "topaz", false,
            UniformInt.of(6, 14), null, null,
            "mythicupgrades:topaz_ore", "mythicupgrades:deepslate_topaz_ore"),
    OCCULTISM_SILVER("occultism_silver", "occultism", "occultism_silver", false,
            ConstantInt.of(0), null, null,
            "occultism:silver_ore", "occultism:silver_ore_deepslate"),
    URANINITE("uraninite", "powah", "uraninite", false,
            ConstantInt.of(0), null, new float[] {3.2F, 8.0F, 4.5F, 3.0F},
            "powah:uraninite_ore", "powah:deepslate_uraninite_ore"),
    URANINITE_DENSE("uraninite_dense", "powah", "uraninite_dense", false,
            ConstantInt.of(0), null, new float[] {4.0F, 8.0F, 4.5F, 3.0F},
            "powah:uraninite_ore_dense", "powah:deepslate_uraninite_ore_dense"),
    URANINITE_POOR("uraninite_poor", "powah", "uraninite_poor", false,
            ConstantInt.of(0), null, new float[] {3.0F, 8.0F, 4.5F, 3.0F},
            "powah:uraninite_ore_poor", "powah:deepslate_uraninite_ore_poor"),
    BORT("bort", "silentgear", "bort", false,
            UniformInt.of(3, 7), null, new float[] {4.0F, 10.0F, 4.0F, 10.0F},
            "silentgear:bort_ore", "silentgear:deepslate_bort_ore"),
    ALEXANDRITE("alexandrite", "silentgems", "alexandrite", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:alexandrite_ore", "silentgems:deepslate_alexandrite_ore"),
    SILENTS_AQUAMARINE("silents_aquamarine", "silentgems", "silents_aquamarine", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:aquamarine_ore", "silentgems:deepslate_aquamarine_ore"),
    CHAOS("chaos", "silentgems", "chaos", false,
            UniformInt.of(3, 7), null, new float[] {5.0F, 3.0F, 6.0F, 3.0F},
            "silentgems:chaos_ore", "silentgems:deepslate_chaos_ore"),
    GARNET("garnet", "silentgems", "garnet", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:garnet_ore", "silentgems:deepslate_garnet_ore"),
    HELIODOR("heliodor", "silentgems", "heliodor", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:heliodor_ore", "silentgems:deepslate_heliodor_ore"),
    IOLITE("iolite", "silentgems", "iolite", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:iolite_ore", "silentgems:deepslate_iolite_ore"),
    OPAL("opal", "silentgems", "opal", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:opal_ore", "silentgems:deepslate_opal_ore"),
    SILENTS_PERIDOT("silents_peridot", "silentgems", "silents_peridot", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:peridot_ore", "silentgems:deepslate_peridot_ore"),
    SILENTS_RUBY("silents_ruby", "silentgems", "ruby", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:ruby_ore", "silentgems:deepslate_ruby_ore"),
    SILENTS_SAPPHIRE("silents_sapphire", "silentgems", "sapphire", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:sapphire_ore", "silentgems:deepslate_sapphire_ore"),
    SILENTS_SILVER("silents_silver", "silentgems", "silents_silver", false,
            ConstantInt.of(0), null, null,
            "silentgems:silver_ore", "silentgems:deepslate_silver_ore"),
    SILENTS_TOPAZ("silents_topaz", "silentgems", "silents_topaz", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:topaz_ore", "silentgems:deepslate_topaz_ore"),
    TURQUOISE("turquoise", "silentgems", "turquoise", false,
            UniformInt.of(1, 5), null, null,
            "silentgems:turquoise_ore", "silentgems:deepslate_turquoise_ore"),
    TECHREBORN_BAUXITE("techreborn_bauxite", "techreborn", "techreborn_bauxite", false,
            ConstantInt.of(0), null, null,
            "techreborn:bauxite_ore", "techreborn:deepslate_bauxite_ore"),
    CINNABAR("cinnabar", "techreborn", "cinnabar", true,
            ConstantInt.of(0), null, null,
            "techreborn:cinnabar_ore"),
    GALENA("galena", "techreborn", "galena", false,
            ConstantInt.of(0), null, null,
            "techreborn:galena_ore", "techreborn:deepslate_galena_ore"),
    IRIDIUM("iridium", "techreborn", "iridium", false,
            ConstantInt.of(0), null, null,
            "techreborn:iridium_ore", "techreborn:deepslate_iridium_ore"),
    TECHREBORN_LEAD("techreborn_lead", "techreborn", "techreborn_lead", false,
            ConstantInt.of(0), null, null,
            "techreborn:lead_ore", "techreborn:deepslate_lead_ore"),
    PYRITE("pyrite", "techreborn", "pyrite", true,
            ConstantInt.of(0), null, null,
            "techreborn:pyrite_ore"),
    TECHREBORN_RUBY("techreborn_ruby", "techreborn", "techreborn_ruby", false,
            UniformInt.of(2, 6), null, null,
            "techreborn:ruby_ore", "techreborn:deepslate_ruby_ore"),
    TECHREBORN_SAPPHIRE("techreborn_sapphire", "techreborn", "techreborn_sapphire", false,
            UniformInt.of(2, 6), null, null,
            "techreborn:sapphire_ore", "techreborn:deepslate_sapphire_ore"),
    TECHREBORN_SILVER("techreborn_silver", "techreborn", "techreborn_silver", false,
            ConstantInt.of(0), null, null,
            "techreborn:silver_ore", "techreborn:deepslate_silver_ore"),
    SPHALERITE("sphalerite", "techreborn", "sphalerite", true,
            ConstantInt.of(0), null, null,
            "techreborn:sphalerite_ore"),
    TECHREBORN_TIN("techreborn_tin", "techreborn", "techreborn_tin", false,
            ConstantInt.of(0), null, null,
            "techreborn:tin_ore", "techreborn:deepslate_tin_ore"),
    TECHREBORN_URANIUM("techreborn_uranium", "techreborn", "techreborn_uranium", false,
            ConstantInt.of(0), null, null,
            "techreborn:uranium_ore", "techreborn:deepslate_uranium_ore"),
    // END GENERATED modded kinds
    ;

    private final String id;
    private final IntProvider xp;
    private final IntProvider deepslateXp;
    private final String modId;
    private final Identifier stoneOre;
    private final Identifier deepslateOre;
    private final List<Identifier> extraForms;
    private final Identifier stoneStrength;
    private final Identifier deepslateStrength;
    private final float[] strength;
    private final String seamlessOresId;
    private final List<String> seamlessOresHosts;

    /** A vanilla overworld ore: minecraft:X_ore and minecraft:deepslate_X_ore. */
    OreKind(String id, IntProvider xp) {
        this(id, xp, null, Identifier.withDefaultNamespace(id + "_ore"),
                Identifier.withDefaultNamespace("deepslate_" + id + "_ore"),
                Identifier.withDefaultNamespace(id + "_ore"),
                Identifier.withDefaultNamespace("deepslate_" + id + "_ore"),
                // Written out here: an enum constructor cannot read a static field of its own enum,
                // which is still unset while the constants are built.
                List.of("granite", "diorite", "andesite", "tuff"));
    }

    OreKind(String id, IntProvider xp, String modId, Identifier stoneOre, Identifier deepslateOre,
            Identifier stoneStrength, Identifier deepslateStrength, List<String> seamlessOresHosts) {
        this.id = id;
        this.xp = xp;
        this.deepslateXp = null;
        this.modId = modId;
        this.stoneOre = stoneOre;
        this.deepslateOre = deepslateOre;
        this.extraForms = List.of();
        this.stoneStrength = stoneStrength;
        this.deepslateStrength = deepslateStrength;
        this.strength = null;
        // Seamless Ores names its nether gold after the metal alone: basalt_gold_ore.
        this.seamlessOresId = "nether_gold".equals(id) ? "gold" : id;
        this.seamlessOresHosts = seamlessOresHosts;
    }

    /**
     * Another mod's ore. {@code forms} are its blocks, stone form first; a nether ore has one.
     * {@code strength} is {hardness, resistance, deepslate hardness, deepslate resistance} where the mod
     * sets its own, or null for the vanilla ore convention, which a stone and a deepslate iron ore carry.
     * {@code seamlessOresId} is the ore's name in Seamless Ores' block ids (granite_galena_ore), which can
     * differ from ours: ours must be unique across every host, Seamless Ores' only per host.
     */
    OreKind(String id, String modId, String seamlessOresId, boolean nether, IntProvider xp,
            IntProvider deepslateXp, float[] strength, String... forms) {
        this.id = id;
        this.xp = xp;
        this.deepslateXp = deepslateXp;
        this.modId = modId;
        this.stoneOre = Identifier.parse(forms[0]);
        this.deepslateOre = forms.length > 1 ? Identifier.parse(forms[1]) : null;
        this.extraForms = forms.length > 2
                ? Arrays.stream(forms, 2, forms.length).map(Identifier::parse).toList() : List.of();
        this.stoneStrength = Identifier.withDefaultNamespace(nether ? "nether_quartz_ore" : "iron_ore");
        this.deepslateStrength = nether ? null : Identifier.withDefaultNamespace("deepslate_iron_ore");
        this.strength = strength;
        this.seamlessOresId = seamlessOresId;
        // Seamless Ores' hosts of a nether ore, and of an overworld one. An id it never registered (a
        // stone-tier ore has no tuff variant) is simply not found when the forms are looked up.
        this.seamlessOresHosts = nether ? List.of("basalt", "blackstone") : List.of("granite", "diorite", "andesite", "tuff");
    }

    /** Id fragment, e.g. {@code iron} in {@code blockus_limestone_iron_ore}. */
    public String id() {
        return id;
    }

    /** The XP this ore drops in a host of the given strength. */
    public IntProvider xp(HostStone.Strength host) {
        return host == HostStone.Strength.DEEPSLATE && deepslateXp != null ? deepslateXp : xp;
    }

    /** The ore's own mod, or null for vanilla's. */
    public String modId() {
        return modId;
    }

    /** Whether this ore exists in this game: always for vanilla's, only with its mod for a modded one. */
    public boolean isLoaded() {
        return modId == null || Services.PLATFORM.isModLoaded(modId);
    }

    /** Every block that IS this ore before a stone swallows it: the stone form, then the deepslate one. */
    public List<Identifier> forms() {
        final List<Identifier> forms = new ArrayList<>(3);
        forms.add(stoneOre);
        if (deepslateOre != null) {
            forms.add(deepslateOre);
        }
        forms.addAll(extraForms);
        return List.copyOf(forms);
    }

    /** Seamless Ores' own variants of this ore, which a modded stone swallows just the same. */
    public List<Identifier> seamlessOresForms() {
        return seamlessOresHosts.stream()
                .map(host -> Identifier.fromNamespaceAndPath("seamlessores", host + "_" + seamlessOresId + "_ore"))
                .toList();
    }

    /**
     * The vanilla block whose properties a variant copies: hardness, blast resistance and the tool
     * requirement for vanilla ores and zinc, the rest for a modded one. Vanilla, so it is registered
     * before we are; the nether ores have one strength whatever the host.
     */
    public Identifier strengthSource(HostStone.Strength host) {
        return host == HostStone.Strength.DEEPSLATE && deepslateStrength != null ? deepslateStrength : stoneStrength;
    }

    /**
     * {hardness, resistance} this ore's own mod sets in a host of the given strength, or null where it
     * follows the vanilla ore convention and {@link #strengthSource} already carries it.
     */
    public float[] ownStrength(HostStone.Strength host) {
        if (strength == null) {
            return null;
        }
        return host == HostStone.Strength.DEEPSLATE
                ? new float[] {strength[2], strength[3]} : new float[] {strength[0], strength[1]};
    }

    /** Redstone ore is a RedStoneOreBlock (lit state, random ticks), not a DropExperienceBlock. */
    public boolean redstoneLike() {
        return this == REDSTONE;
    }
}
